import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const foods = [
  { id: 1, name: 'Truffle Mushroom Pasta', place: 'Olive & Oak', price: 18.5, time: '25–30 min', emoji: '🍝', color: '#fbf0df' },
  { id: 2, name: 'Smoky Burger Stack', place: 'Bun & Barrel', price: 15.9, time: '20–25 min', emoji: '🍔', color: '#fce4d9' },
  { id: 3, name: 'Spicy Salmon Roll', place: 'Kumo Sushi', price: 16.2, time: '30–35 min', emoji: '🍣', color: '#e6f3ec' },
  { id: 4, name: 'Garden Mezze Bowl', place: 'Nourish Kitchen', price: 13.8, time: '15–20 min', emoji: '🥗', color: '#e9f3d8' },
];
const steps = ['Order placed', 'Kitchen is cooking', 'Picked up', 'On the way', 'Delivered'];

function App() {
  const [page, setPage] = useState('home'); const [cart, setCart] = useState([]); const [tracking, setTracking] = useState(3); const [role, setRole] = useState('Customer'); const [toast, setToast] = useState('');
  const total = cart.reduce((a,x) => a + x.price, 0); const activeOrder = cart.length > 0;
  useEffect(() => { if (toast) { const t = setTimeout(()=>setToast(''), 2600); return ()=>clearTimeout(t); }}, [toast]);
  useEffect(() => { if (!activeOrder || tracking >= 4) return; const t = setInterval(()=>setTracking(x=>Math.min(4,x+1)), 7500); return ()=>clearInterval(t); }, [activeOrder, tracking]);
  const add = food => { setCart(c=>[...c, food]); setToast(`${food.name} added to your order`); };
  const nav = p => { setPage(p); window.scrollTo({top:0, behavior:'smooth'}); };
  return <><header><button className="logo" onClick={()=>nav('home')}><span>✦</span> platepath</button><div className="location">⌖ Deliver to <b>Indiranagar, Bengaluru</b>⌄</div><nav><button className={page==='home'?'on':''} onClick={()=>nav('home')}>Discover</button><button onClick={()=>nav('restaurants')}>Restaurants</button><button onClick={()=>nav('dash')}>Dashboard</button></nav><button className="cart" onClick={()=>nav('track')}>🛍 <i>{cart.length}</i></button><button className="avatar">KS</button></header>
  {toast && <div className="toast">✓ {toast}</div>}
  {page==='home' && <Home add={add} nav={nav}/>} {page==='restaurants' && <Restaurants add={add}/>} {page==='track' && <Track cart={cart} total={total} tracking={tracking} setTracking={setTracking} nav={nav}/>} {page==='dash' && <Dashboard role={role} setRole={setRole} nav={nav}/>} 
  <footer><div className="logo"><span>✦</span> platepath</div><p>Thoughtful food delivery, from the neighbourhood to your door.</p><small>© 2026 PlatePath • Live order intelligence</small></footer></>;
}
function Home({add, nav}) { return <main><section className="hero"><div><p className="eyebrow">DELIVERED WITH INTENTION</p><h1>Good food.<br/><em>Right on time.</em></h1><p className="sub">A better way to discover local favourites and follow every delicious detail, all the way home.</p><button className="primary" onClick={()=>nav('restaurants')}>Explore restaurants <b>→</b></button></div><div className="hero-plate"><div className="ring"></div><div className="plate">🥘</div><span className="tag one">✦ 4.9 rated</span><span className="tag two">⚡ 28 min away</span></div></section><section className="feature-strip"><span>◉ Live order tracking</span><span>♧ Curated local kitchens</span><span>♢ Secure checkout</span></section><section className="section"><div className="section-title"><div><p className="eyebrow">PICKED FOR YOU</p><h2>Worth staying in for</h2></div><button className="textbtn" onClick={()=>nav('restaurants')}>See all restaurants →</button></div><div className="foodgrid">{foods.map(f=><FoodCard key={f.id} f={f} add={add}/>)}</div></section></main> }
function FoodCard({f, add}) { return <article className="foodcard"><div className="foodpic" style={{background:f.color}}><span>{f.emoji}</span><button onClick={()=>add(f)}>+</button></div><div className="foodinfo"><p>{f.place} <span>★ 4.8</span></p><h3>{f.name}</h3><div><b>${f.price.toFixed(2)}</b><small>{f.time}</small></div></div></article> }
function Restaurants({add}) { return <main className="section browse"><p className="eyebrow">YOUR NEIGHBOURHOOD, SERVED</p><h1>Find your next favourite.</h1><div className="filters"><button className="active">All</button><button>Fast delivery</button><button>Top rated</button><button>Vegetarian</button><button>Under 30 min</button></div><div className="foodgrid">{[...foods,...foods].map((f,i)=><FoodCard key={i} f={{...f,id:i}} add={add}/>)}</div></main> }
function Track({cart,total,tracking,setTracking,nav}) { const eta = tracking===4 ? 'Delivered' : `${Math.max(2, 19-(tracking*4))}–${Math.max(5, 24-(tracking*4))} min`; return <main className="tracking"><div className="trackhead"><p className="eyebrow">ORDER PP-49281</p><h1>{tracking===4 ? 'Enjoy your meal!' : 'Your order is on its way.'}</h1><p>{tracking===4 ? 'Delivered to your door at 7:04 PM.' : 'Arjun is bringing your order from Olive & Oak.'}</p></div><div className="track-layout"><section className="map"><div className="street s1"></div><div className="street s2"></div><div className="street s3"></div><div className="block b1"></div><div className="block b2"></div><div className="park">Cubbon<br/>Park</div><div className="pin restaurant">●<label>Olive & Oak</label></div><div className="route"></div><div className="pin rider">🛵<label>Arjun</label></div><div className="pin home">⌂<label>Your place</label></div><div className="live">● LIVE LOCATION</div></section><aside className="ordercard"><div className="riderbox"><div className="rider">🧑🏽</div><div><b>Arjun Patel</b><p>Delivery partner · ★ 4.9</p></div><button>☎</button></div><div className="eta"><span>{tracking===4?'✓':'🛵'}</span><div><small>{tracking===4?'ORDER COMPLETE':'ARRIVING IN'}</small><strong>{eta}</strong></div></div><div className="progress">{steps.map((x,i)=><div className={i<=tracking?'done':''} key={x}><i>{i<tracking?'✓':i+1}</i><span>{x}</span></div>)}</div><div className="summary"><b>Your order</b>{cart.length?cart.map((x,i)=><p key={i}>{x.emoji} {x.name}<strong>${x.price.toFixed(2)}</strong></p>):<p>🥘 Truffle Mushroom Pasta <strong>$18.50</strong></p>}<hr/><p>Delivery <strong>$2.00</strong></p><h3>Total <strong>${(total||18.5+2).toFixed(2)}</strong></h3></div><button className="primary wide" onClick={()=>{setTracking(Math.min(4,tracking+1));}}>Update delivery demo</button></aside></div><button className="back" onClick={()=>nav('home')}>← Continue browsing</button></main> }
function Dashboard({role,setRole,nav}) { const data = {Customer:['Welcome back, Kulvinder','1 active order','12 orders'],Restaurant:['Olive & Oak overview','$1,842 today','28 open orders'],Driver:['Good evening, Arjun','₹1,280 earned','4 deliveries']}[role]; return <main className="section dashboard"><div className="dash-top"><div><p className="eyebrow">ROLE-BASED WORKSPACE</p><h1>{data[0]}</h1><p className="sub">Everything you need, in one considered place.</p></div><select value={role} onChange={e=>setRole(e.target.value)}>{['Customer','Restaurant','Driver','Admin'].map(x=><option key={x}>{x}</option>)}</select></div><div className="metrics"><div><small>{role==='Driver'?'THIS WEEK':'TODAY'}</small><strong>{data[1]}</strong><span>↗ 12.4% vs last week</span></div><div><small>{role==='Customer'?'ALL TIME':'IN PROGRESS'}</small><strong>{data[2]}</strong><span>Everything is on track</span></div><div><small>LIVE STATUS</small><strong className="green">● Connected</strong><span>Real-time updates active</span></div></div><div className="dashgrid"><section className="panel"><div className="panelhead"><h2>{role==='Customer'?'Current order':'Live orders'}</h2><button className="textbtn" onClick={()=>nav('track')}>View all →</button></div><div className="orderrow"><div className="mini">🍝</div><div><b>Olive & Oak</b><p>Truffle Mushroom Pasta · PP-49281</p></div><span className="status">On the way</span></div><div className="orderrow"><div className="mini">🥗</div><div><b>Nourish Kitchen</b><p>Garden Mezze Bowl · PP-49270</p></div><span className="status muted">Preparing</span></div></section><section className="panel insight"><p className="eyebrow">REAL-TIME PULSE</p><h2>Orders are moving smoothly.</h2><div className="bars">{[42,68,48,82,63,94,70].map((x,i)=><i key={i} style={{height:x+'%'}}></i>)}</div><small>Orders across the last 7 hours</small></section></div></main> }
createRoot(document.getElementById('root')).render(<App/>);
